server:
  servlet:
    context-path: /snail-wp
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: select 1
      connection-test-query: select 1
      connection-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 20
      minimum-idle: 10
    password: seblong2017
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://sh-cdb-0rm6u44o.sql.tencentcdb.com:62199/seblong?characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&autoReconnectForPools=true&createDatabaseIfNotExists=true&useSSL=true
    username: root
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
          use_second_level_cache: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        generate_statistics: false
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
      hibernate_use_sql_comments: false
    show-sql: true
snail:
  wp:
    redis:
      host: 182.254.245.148
      port: 6379
      password: seblong
      maxTotal: 32
      maxIdle: 8
      testOnIdle: true
    mongodb:
      user:
        url: mongodb://root:seblong2015@182.254.245.148:27017/seblong?authSource=admin&maxPoolSize=3000&waitQueueMultiple=500&waitQueueTimeoutMS=5000
swagger:
  enabled: true